services:
    diglin_oro.api.client_factory:
        class: Diglin\OAuth2Oro\Client\Api\ClientOAuthFactory
        arguments:
            - '\Diglin\OAuth2Oro\Client\Api\ClientOAuth'
            - '@diglin_oro.api.client_settings'

    diglin_oro.api.client_settings:
        class: Diglin\OAuth2Oro\Client\Api\ClientOAuthSettings
        public: true
        calls:
            - [setContainer, ["@service_container"]]
    
