services:
    diglin_oauth2_oro.api.client_factory:
        class: Diglin\OAuth2OroBundle\Api\ClientOAuthFactory
        arguments:
            - '\Diglin\OAuth2OroBundle\Api\ClientOAuth'
            - '@diglin_oauth2_oro.api.client_settings'

    diglin_oauth2_oro.api.client_settings:
        class: Diglin\OAuth2OroBundle\Api\ClientOAuthSettings
        public: true
        arguments:
            - ~
            - ~
            - ~
            - ~
            - ~
            - ~

